### ISSUE TITLE
Sidebar Lists on Building Pages are Not the Same

### ISSUE THREAD

**Issue by mgamlem3** [mgamlem3/Energy-Dashboard#101] opened 2019-04-10 18:51 UTC
**Describe the bug**
Lists of buildings on both pages are not the same.

**Expected behavior**
Should be consistent across both pages. When fixed, follow new common resource format as seen in #100 on `testing`

**Comment by Link196** [comment] 2019-04-11 00:19
Where is the issue? It's probably obvious, but I'm not seeing it.

**Comment by mgamlem3** [comment] 2019-04-11 00:59
If you look at the two pages tagged in the issue, you will be able to see that they do not contain the same buildings.

**Comment by Link196** [comment] 2019-04-11 01:08
I looked at both pages on the testing branch and on my local copy; I even made a spreadsheet to compare the two lists. I'm still not seeing any differences. 
I'm assuming the issue is showing up for you on the testing branch?

**Comment by mgamlem3** [comment] 2019-04-11 01:49
https://github.com/mgamlem3/Energy-Dashboard/blob/testing/src/components/BuildingDetails/buildingDetails.jsx
Compare this to what actually gets shown

**Comment by Link196** [comment] 2019-04-11 02:29
I see your point. I'll look into it.

**Comment by Link196** [comment] 2019-04-11 02:37
Got it. Somehow, all the buildings below Robinson in the list got removed from buildingDetails.jsx

**Comment by mgamlem3** [comment] 2019-04-11 02:43
Strange, not entirely sure what that means or how it happened...

**Comment by Link196** [comment] 2019-04-11 02:45
Thankfully, the whole list was present in buildingDetails.jsx
In any case, I added the missing buildings, and the list looks normal now. I'll commit it soon.

**Comment by Link196** [comment] 2019-04-11 02:52
I just created a PR to fix this issue. It looks like it contains other commits though, so I flagged it for review just to be safe.

**Comment by Link196** [comment] 2019-04-11 21:59
Fixed in #104

**Closed by Link196** 2019-04-11 21:59 UTC
Labels: Building Comparison Page, Building Details Page, Design, bug, priority-normal
